version: '2'

services:
  jenkins:
    image: mariosergioas/jenkins
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - 8085:8080
      - 50000:50000
    volumes:
      - ./data:/var/jenkins_home/.jenkins
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    